ServerRoot "/usr/local/apache2"

Listen 80

ServerName nimbusdocs.local

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dir_module modules/mod_dir.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule rewrite_module modules/mod_rewrite.so

PidFile /usr/local/apache2/logs/httpd.pid

TypesConfig conf/mime.types

User daemon
Group daemon

ErrorLog /usr/local/apache2/logs/error_log

LogLevel warn

DirectoryIndex index.html


# ==========================================================
# VIRTUAL HOST 1
# apachedocs.local
# MARCA PUBLICA
# ==========================================================

<VirtualHost *:80>

    ServerName apachedocs.local

    DocumentRoot "/var/www/apachedocs"

    ErrorLog "/var/log/apache2/nimbusdocs/apachedocs/error.log"

    CustomLog "/var/log/apache2/nimbusdocs/apachedocs/access.log" combined

    <Directory "/var/www/apachedocs">

        Options -Indexes

        AllowOverride None

        Require all granted

    </Directory>

</VirtualHost>


# ==========================================================
# VIRTUAL HOST 2
# nginxdocs.local
# MARCA INTERNA
# ==========================================================

<VirtualHost *:80>

    ServerName nginxdocs.local

    DocumentRoot "/var/www/nginxdocs"

    ErrorLog "/var/log/apache2/nimbusdocs/nginxdocs/error.log"

    CustomLog "/var/log/apache2/nimbusdocs/nginxdocs/access.log" combined

    <Directory "/var/www/nginxdocs">

        Options -Indexes

        AllowOverride None

        Require all granted

    </Directory>

    # Protección del fichero sensible

    <Files "configuracion-nimbus.conf">

        Require all denied

    </Files>

</VirtualHost>


# ==========================================================
# VIRTUAL HOST POR DEFECTO
# DOMINIOS DESCONOCIDOS
# ==========================================================

<VirtualHost *:80>

    ServerName desconocido.local

    DocumentRoot "/var/www/404"

    ErrorLog "/var/log/apache2/nimbusdocs/default-error.log"

    CustomLog "/var/log/apache2/nimbusdocs/default-access.log" combined

    <Directory "/var/www/404">

        Options -Indexes

        AllowOverride None

        Require all granted

    </Directory>

    RewriteEngine On

    RewriteRule ^ - [R=404,L]

</VirtualHost>
