version: '3.8'

services:
  apache-backend:
    build: ./apache
    container_name: nimbus-apache
    networks:
      - nimbus-net

  nginx-proxy:
    build: ./nginx
    container_name: nimbus-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apache-backend
    networks:
      - nimbus-net

networks:
  nimbus-net:
    driver: bridge