# ==================================================
# CONFIGURACION INTERNA DE NIMBUSDOCS
# ==================================================

nombre_empresa=NimbusDocs
entorno=produccion
servidor_documental=apache
zona=interna

# Este fichero contiene información simulada
# y no debe ser accesible públicamente.
